title: cptol
description: Another Compeitive Programming Tools 
theme: jekyll-theme-cayman
url: https://kagemeka.github.io
lsi: false
safe: true
source: [.]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
