name: Fetch Submissions

on:
  schedule:
    - cron: "0 */1 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install apts
        run: |
          sudo apt update
          sudo apt install -y curl wget fonts-noto-cjk
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Fetch my submissions
        run: |
          python3 src
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: fetch algomethod submissions.
